package adaspera.lab1.Models.Mybatis;

public class Topic {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.id
     *
     * @mbg.generated Wed Mar 12 11:37:10 EET 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.name
     *
     * @mbg.generated Wed Mar 12 11:37:10 EET 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.optlockversion
     *
     * @mbg.generated Wed Mar 12 11:37:10 EET 2025
     */
    private Integer optlockversion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.id
     *
     * @return the value of topic.id
     *
     * @mbg.generated Wed Mar 12 11:37:10 EET 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.id
     *
     * @param id the value for topic.id
     *
     * @mbg.generated Wed Mar 12 11:37:10 EET 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.name
     *
     * @return the value of topic.name
     *
     * @mbg.generated Wed Mar 12 11:37:10 EET 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.name
     *
     * @param name the value for topic.name
     *
     * @mbg.generated Wed Mar 12 11:37:10 EET 2025
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.optlockversion
     *
     * @return the value of topic.optlockversion
     *
     * @mbg.generated Wed Mar 12 11:37:10 EET 2025
     */
    public Integer getOptlockversion() {
        return optlockversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.optlockversion
     *
     * @param optlockversion the value for topic.optlockversion
     *
     * @mbg.generated Wed Mar 12 11:37:10 EET 2025
     */
    public void setOptlockversion(Integer optlockversion) {
        this.optlockversion = optlockversion;
    }
}